### ISSUE TITLE
Revised API for file_handler method and base class

### ISSUE THREAD

**Issue by AndyPro720** [AndyPro720/GroupAssembler#2]
The intent of this document is to set a standard for the definition for the assembler so that it can be reused across different platforms.

**I care about the definitions and not about the implementations**
--- 
1. class name : `Assembler`
2. public variable name : `instructions`
3. first method name: `file_handler`
4. second method: `cleaner`
---
* Make sure to match the case
* As a good practice have your objects and variables within the methods have *useful* names as well.
* Upon successful commit` comment me below here` so that I can close this issue.

**Comment by rish292** [comment]
@AndyPro720 done

**Comment by AndyPro720** [comment]
@rish292 test
